[package]
name = "http_client"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "*", features = ["json", "native-tls"] }
tokio = { version = "*", features = ["full"] }
serde_json = "*"
rand = "*"
hex = "*"
futures = "*"
num_cpus = "*"
cpu-time = "*"
