[package]
name = "http_client"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json", "native-tls"] }
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
rand = "0.8"
hex = "0.4"
futures = "0.3"
num_cpus = "1.15"
cpu-time = "1.0"
